### ISSUE TITLE
Laravel version 8

### ISSUE THREAD

**Issue by dalholm** [caffeinated/themes#109]
Hello,
I just found this package and it seems to be the solution for my wishes, but for what i can see this package is not supported for Laravel 8. Is this in the roadmap?  :)

**Comment by AlessandroCuba** [comment]
I also expect it

**Comment by dalholm** [comment]
@AlessandroCuba i have added a PR in the meantime you could use [this repo](https://github.com/dalholm/themes)

**Comment by AlessandroCuba** [comment]
@dalholm danke.. thank

**Comment by Plasto13** [comment]
when do they merge??

**Comment by dalholm** [comment]
@Plasto13 i have made another package for this  [here](https://github.com/dalholm/laravel-themes)

**Comment by Plasto13** [comment]
> @Plasto13 i have made another package for this [here](https://github.com/dalholm/laravel-themes)

thanx
