### ISSUE TITLE
How set a layout in a controller ? 

### ISSUE THREAD

**Issue by khanhnam99** [caffeinated/themes#13]
How set a layout in a controller ?

Here my controller

namespace App\Modules\Blog\Http\Controllers;
use App\Http\Controllers\Controller;
class BlogController extends Controller{
    public function home()
    {
        return '111';
        exit;
    }
}

**Comment by kaidesu** [comment]
In your controllers constructor, use:

```php
Theme::setLayout('reference.to.layout');
```

This would be best placed in your base controller.

**Comment by kaidesu** [comment]
See here for more information: https://github.com/caffeinated/themes/wiki/Views-And-Responses#extending-theme-views
