### ISSUE TITLE
how create @extends pages in master.blade.php

### ISSUE THREAD

**Issue by khanhnam99** [caffeinated/themes#14]
I have 3 pages
page.blade.php
page2.blade.php
page3.blade.php
in folder laravel\app\Modules\Blog\Resources\Views

master.blade.php in folder laravel\public\themes\bootstrap\views

how include page.blade.php  include into to master.blade.php

**Comment by kaidesu** [comment]
My advice is to spend some time learning the basics of Laravel before jumping into trying to make use of this package. Laravel by itself is more than capable to building out a blog application.

For questions like these, I'd like to point you to the following communities that can help you out more than I can:
- [Laravel.IO](http://laravel.io/forum)
- [Laracasts Forum](https://laracasts.com/discuss)

Laracasts is also an excellent learning resource that I highly recommend. In fact, the following series is completely free and provides an excellent introduction to the basics of Laravel:
- [Laravel 5 Fundamentals](https://laracasts.com/series/laravel-5-fundamentals)

The Laravel documentation is also an excellent resource, here's the page specifically on the Blade templating system:
- [Blade Templates](http://laravel.com/docs/5.1/blade)

I hope all of this helps and good luck in your learning endeavors.
