### ISSUE TITLE
how take a css , javascript in in folder with module htdocs\laravel\public\themes\bootstrap\assets\css\

### ISSUE THREAD

**Issue by khanhnam99** [caffeinated/themes#16]
how take a css , javascript in in folder with module htdocs\laravel\public\themes\bootstrap\assets\css\

please help me!

**Comment by kaidesu** [comment]
Please ask on one of the Laravel forums:
- [Laravel.IO](http://laravel.io/forum)
- [Laracasts Forum](https://laracasts.com/discuss)
