### ISSUE TITLE
feature request: theme, shared assets

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/themes#19]
Would it be possible to add the ability to share assets between themes but yet still maintain the ability to have assets only for that theme?

Or ... did I miss something again :smile:

**Comment by kaidesu** [comment]
What kind of assets?

For CSS/JS/Images you can simply reference them directly per normal (`/themes/theme1/assets/css/bootstrap.css`, etc.)

For themes, you can define a parent theme in which view files from the parent theme will become a fallback view.

Theme components are also shared in a parent/child relationship (where the parent's components are accessible from within the child theme).

**Comment by illuminate3** [comment]
Thanks!
I'll look into the parent theme ability.
