### ISSUE TITLE
@extends and @include not working?

### ISSUE THREAD

**Issue by drjoju** [caffeinated/themes#2]
Hello,

We are trying to use the themes but we have an issue.

In the controller we call the view with
return Theme::view('pages.auth.login');
And the view has the next code
@extends('layouts.simple')
@section('content')

            <div class="body bg-gray">

                @include ('includes.errors', array('errors' => $errors))
           </div>
@stop

When we call the page, and error appears.

ErrorException in FileViewFinder.php line 140: View [layouts.simple] not found. (View: /home/vagrant/www/Laravel5/web/public/themes/admin/views/pages/auth/login.blade.php)

we have the simple.blade.php in the directory.
/home/vagrant/www/Laravel5/web/public/themes/admin/views/layouts/simple.blade.php

Please, can you confirm the we can use the @extends and @include Blade methods in a view.

Thanks in advance

**Comment by kaidesu** [comment]
If you're trying to include or extend a view *from* your theme, you must use the theme's namespace when referencing the view file:

```php
@extends ('admin::layouts.simple')

@include('admin::includes.errors', array('errors' => $errors))
```

**Comment by drjoju** [comment]
It works!. I think it would be interesting that you include an example in the documentation.
Thanks!!! 

Best regards

**Comment by illuminate3** [comment]
I have my "general" partials as:
resources/views/_partials/extra.blade.php

```
	@include('_partials.modal')
```

Adding the module namespace throws a not found error.

How should I call my _partials from my view?

Thanks :smile:

**Comment by guillaume23** [comment]
Hi every one, i can't extends a layout from a template in a caffeinated module, it's normal ? 
```@extends('gentella::layout')

don't work

and 
```$theme_layout = Theme::setLayout('layout');

don't work too
```$theme_layout = Theme::setLayout('gentella::layout');

an idea ? 
Thanks
