### ISSUE TITLE
double compacting variables

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/themes#20]
I've noticed that compacting variables twice is causing the second set to be skipped.
If I don't set the theme method on the view I can compact variables at both the repository and controller levels.

This really isn't an issue so to say but I like trying to keep view variables away from the model/repository layers. (I prefer a strict MVC old school approach which ends up with a slightly fatter controller and a slimmer model.)

Here's what I got:

view:
```
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="{{ trans('kotoba::general.command.close') }}"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title">
		{{ $modal_title }}
		</h4>
	</div>

	<div class="modal-body">
		<p>
		{{ $modal_body }}
		</p>
	</div>
```

## working solution:

controller:
```
		return Theme::View('menus::menus.edit',
			$this->menu_repo->edit($id));
```

repository:
```
		$menu = $this->model->find($id);
		$lang = Session::get('locale');

		$modal_title = trans('kotoba::general.command.delete');
		$modal_body = trans('kotoba::general.ask.delete');
		$modal_route = 'admin.menus.destroy';
		$modal_id = $id;
		$model = '$menu';

		return compact(
			'lang',
			'menu',
			'modal_title',
			'modal_body',
			'modal_route',
			'modal_id',
			'model'
			);
```

The issue I have with this is that I'm pushing view variables down into the Model/Repository layer. 

## broken method

controller:
```
		$modal_title = trans('kotoba::general.command.delete');
		$modal_body = trans('kotoba::general.ask.delete');
		$modal_route = 'admin.menus.destroy';
		$modal_id = $id;
		$model = '$menu';

		return Theme::View('menus::menus.edit',
			$this->menu_repo->edit($id),
				compact(
					'modal_title',
					'modal_body',
					'modal_route',
					'modal_id',
					'model'
			));
```

repository:
```
		$menu = $this->model->find($id);
		$lang = Session::get('locale');

		return compact('menu', 'lang');
```

Just wondering what your thoughts are on this :smile:

**Comment by kaidesu** [comment]
```php
return Theme::View('menus::menus.edit',
            $this->menu_repo->edit($id),
                compact(
                    'modal_title',
                    'modal_body',
                    'modal_route',
                    'modal_id',
                    'model'
            ));
```

Couple things I see wrong with this.

1. `$this->menu_repo->edit($id)`: Generally you don't want to pass through a method directly like this. Assign it to a variable first.
3. Your second `compact` is ignored because there is no third parameter to be passed through the method. This is the same as passing data to Laravel's *vanilla* `views`.

```php
Theme::view($view, $data);
```

When passing information, `$data` should be an array with key/value pairs. This can be done either in an array format:

```php
Theme::view('greetings', ['name' => 'Victoria']);
```

Or through the compact method:

```php
$name = 'Victoria';

Theme::view('greetings', compact('name'));
```
