### ISSUE TITLE
Child/parent inheritance

### ISSUE THREAD

**Issue by appdezign** [caffeinated/themes#23]
I have installed caffeinated themes (and caffeinated modules) and everything works as it should. However, I can't seem to find the Child/parent inheritance in the documentation. And this is exactly what I'm looking for: a simple theme manager with parent/child inheritance.

**Comment by kaidesu** [comment]
Ah, yeah looks like I missed that in the documentation.

Within your theme's manifest file, simply set a `parent` key to the slug of the parent theme you'd like to inherit.

```json
{
	"name": "Darkly",
	"description": "Darkly bootstrap theme.",
	"author": "Kai",
	"version": "1.0.0",
	"parent": "bootstrap"
}
```

Caffeinated Themes will then load any missing view files from the parent theme. Does this make sense?

**Comment by appdezign** [comment]
That makes perfect sense. And it works now. Thanks again.
