### ISSUE TITLE
Theme::asset() is always prepend '/' to the generated link

### ISSUE THREAD

**Issue by AkramBerkawy** [caffeinated/themes#24]
I have to config my themes to have base path as URL, i.e.:
`'base' => url( 'public/themes'),`

now the generated asset URL when calling Theme::asset() is:
`"/http://localhost:8888/laravel/....`

any possible solution ?
Thanks.

**Comment by UnderlineWords** [comment]
I sent a pull request about it.
https://github.com/caffeinated/themes/pull/28
