### ISSUE TITLE
Change the resource/views to resource/views/defaultTheme

### ISSUE THREAD

**Issue by lyubb** [caffeinated/themes#26]
Any way to do this?

Actually the cascade-style to finding the desired view file works fine but if I need to load `public/themes/active-theme/views/welcome.blade.php` file but not found in theme, I want to load from `resources/views/defaultTheme/welcome.blade.php` instead `resources/views/welcome.blade.php`

Thanks, sorry for my bad english and my ignorance. Greetings.

**Comment by kaidesu** [comment]
No worries - the package does support this out of the box already (it's just not documented at the moment, so sorry about that!)

All you need to do is, within your theme's manifest file, specify a **parent** key that points to the theme (by its slug) you wish to designate as the parent.

```json
{
    ...
    "parent": "bootstrap",
    ...
}
```

Now, any views that don't exist within your currently active theme will first fall back to the specified parent theme.

Let me know if you have any further questions!
