### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by avramovic** [caffeinated/themes#27]
When I tried to upgrade my app to L5.2 following [this document](https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0), it failed on the first step (composer update) because Laravel 5.2 changed some dependencies with newer versions while it seems this module is not compatible with those.

```
  Problem 1
    - Conclusion: remove laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.5
    - caffeinated/themes v2.0 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25,v5.1.6, v5.1.8].
    - caffeinated/themes v2.0.1 requires illuminate/config 5.1.* -> satisfiableby illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8].
    - don't install illuminate/config v5.1.1|don't install laravel/framework v5.2.5
    - don't install illuminate/config v5.1.13|don't install laravel/framework v5.2.5
    - don't install illuminate/config v5.1.16|don't install laravel/framework v5.2.5
    - don't install illuminate/config v5.1.2|don't install laravel/framework v5.2.5
    - don't install illuminate/config v5.1.20|don't install laravel/framework v5.2.5
    - don't install illuminate/config v5.1.22|don't install laravel/framework v5.2.5
    - don't install illuminate/config v5.1.25|don't install laravel/framework v5.2.5
    - don't install illuminate/config v5.1.6|don't install laravel/framework v5.2.5
    - don't install illuminate/config v5.1.8|don't install laravel/framework v5.2.5
    - Installation request for laravel/framework == 5.2.5.0 -> satisfiable by laravel/framework[v5.2.5].
    - Installation request for caffeinated/themes ~2.0 -> satisfiable by caffeinated/themes[v2.0, v2.0.1].
```

I'm not sure should I upgrade to 5.2 anyway but since my project is at the very early beginning I thought I could upgrade before having to refactor any large portion of code (if I decide to upgrade later).

**Comment by diquinnyonk** [comment]
Im guessing it would be something in the new year. Probably already something they are working on.

**Comment by kaidesu** [comment]
Yeah, I'll need to update the dependencies for Laravel 5.2. I'll also be renaming the package to "Theme" rather than "Themes" so I wanted to wrap both of these updates together for v3.0.

See here for more information: http://caffeinated.ninja/blog/news/changes-to-packages

**Comment by avramovic** [comment]
Great! Can't wait for the updates!
