### ISSUE TITLE
Dynamically Extension of Parent Views

### ISSUE THREAD

**Issue by heikobihlmaier** [caffeinated/themes#31]
Hi @kaidesu,

how can I extend a dynamic view ? For example:

In my CMS I have a module "Core". This module integrate for example the view "core.index" and extend the theme "bootstrap::master".

How can I make "bootstrap" dynamically based on the selected customer layout in backend ?

Greetings.

**Comment by heikobihlmaier** [comment]
No suggestion ?

**Comment by kaidesu** [comment]
This is undocumented, but you have access to a variable called `$theme_layout` in all your view files. This variable will automatically update depending on the current theme and layout of you define within your application.

So, you'll be able to use `@extends($theme_layout)`.

Hope this is what you were looking for! And sorry for the delay in a response.
