### ISSUE TITLE
UrlGenerator could not be converted to string

### ISSUE THREAD

**Issue by golfer007** [caffeinated/themes#34]
laravel 5.2

Caffeinated\Themes\Themes.php online 378

Solution : https://github.com/laravel/framework/issues/11479

change url() to url('/')

**Comment by churris43** [comment]
+1 Fixed the problem for me :)

**Comment by UnderlineWords** [comment]
I guess it's fixed in https://github.com/caffeinated/themes/pull/36

**Comment by kaidesu** [comment]
Yup, thanks for catching this @UnderlineWords
