### ISSUE TITLE
Get current theme url

### ISSUE THREAD

**Issue by UnderlineWords** [caffeinated/themes#4]
Hi, how can i get current theme url for using assets?
Thanks

**Comment by thinmy** [comment]
I think you can use Theme::setProperty programmaticaly or set a path to theme manifest.

http://codex.caffeinated.ninja/themes/master/themes/manifest-file#get-manifest-properties

**Comment by kaidesu** [comment]
Hmm, why not use a relative path like:

```html
<link rel="stylesheet" type="text/css" href="/themes/bootstrap/assets/css/bootstrap.min.css">
```

Or am I missing something here?

**Comment by UnderlineWords** [comment]
Yes, relative path is maybe a alternative way. 
But I'm using this for now. It maybe useful :) 

vendor\caffeinated\themes\src\Caffeinated\Themes\Themes.php
..
..
use Illuminate\Support\Facades\URL;
class Themes
{
..
..
public function url() {

	$theme_root = URL::to('/themes');
	$active_theme = $this->getActive();

	$relative_path = $theme_root . '/' . $active_theme;

	return $relative_path;
}
</code>
<link rel="stylesheet" type="text/css" href="{!! Theme::url() !!}/css/bootstrap.min.css">

**Comment by kaidesu** [comment]
I've added both an `asset()` and `secureAsset()` method to remedy this in v1.2. Usage is simple:

```
{!! Theme::asset('themeslug::css/bootstrap.css') !!}

{!! Theme::asset('themeslug::js/bootstrap.js') !!}
```

Be sure to update your theme config file as things have been cleaned up with a few new options added.
