### ISSUE TITLE
How to customize views directory

### ISSUE THREAD

**Issue by skalero01** [caffeinated/themes#44]
Hi, i'd like to customize my views directory to use a subfolder when in the theme was not found the view, so if the view doesn't exist search in views/store folder.

Is there a way to do this? 

Regards

**Comment by UnderlineWords** [comment]
You can define a custom directory in your controller. For example;

```php
// dynamic
return Theme::view($custom_directory .  '.index');

// or
return Theme::view('store.index'); // themes/default/views/store/index.blade.php
```
