### ISSUE TITLE
Issue with components not being rendered

### ISSUE THREAD

**Issue by Reached** [caffeinated/themes#47]
Hi there,

My components are just being rendered as text on my page:

@component_pageheader('My Awesome Page Header')

I am using the default setup as pr. described in the docs:

```
\Component::register('pageheader', function($title) {
    return "<h1 class=\"page-header\">{$title}</h1>";
});
```

In my view:

`@component_pageheader('My Awesome Page Header')`

The components.php file is at the root of my directory, in this case its called "bootstrap". Am I missing something here ?

**Comment by nuno-iglesias** [comment]
Not sure if the "Components" facade is included in the source.

**Comment by kaidesu** [comment]
Sorry, outdated docs - the components feature of the package have been removed - check out the native component/slot feature of 5.4 here: https://laravel.com/docs/5.4/blade#components-and-slots
