### ISSUE TITLE
Issue with installation on laravel 5.3. modules package is already installed 

### ISSUE THREAD

**Issue by mua22** [caffeinated/themes#49]
I'm having some issues with the installation. Can you help with that. Attach is the screenshot
![issue](https://cloud.githubusercontent.com/assets/31942/22183770/26b30b42-e0e7-11e6-95fd-ae8698b234c1.jpg)

**Comment by mua22** [comment]
When I omit the version from the composer require command then your plugin installed correctly. Whats the catch here

**Comment by UnderlineWords** [comment]
Can you send your composer.json screenshot ? Probably, you are trying to install old version of Caffeinated Themes package.
