### ISSUE TITLE
Theme isn't working with Module

### ISSUE THREAD

**Issue by davidweb-co** [caffeinated/themes#5]
Hello, 
I can't use this module https://github.com/caffeinated/modules
Module is return null value when use Theme::view, are you have solution?

Thank you

![2015-03-12_10-08-52](https://cloud.githubusercontent.com/assets/10545032/6611538/ebc6a220-c89f-11e4-9fa4-814c8d711bcf.jpg)

**Comment by kaidesu** [comment]
Should be:

```php
return Theme::view('modules.yourmodule.your.view');
```

**Comment by davidweb-co** [comment]
It's work, thank you.

**Comment by illuminate3** [comment]
clarification:

Theme::getActive() = bootstrap
'path' => public_path('themes'),


Currently it looks like when I do:
```
		return Theme::View('modules.general.landing');
```

the view comes from:
app/Modules/general/Resources/Views/landing.blade

I was hoping that the view would pull from:
public/themes/bootstrap/views/general/landing.blade

**Comment by kaidesu** [comment]
Within your theme, you need to place it within a `modules` directory.

```
public/themes/bootstrap/views/modules/general/landing.blade
```

**Comment by kaidesu** [comment]
Also, if the view file does not exist within your theme, it will fallback to using the view file supplied with your module.

**Comment by illuminate3** [comment]
Still not pulling from my theme directory.
Forward slashes don't work either and for some reason dd(Theme::all()) doesn't show in this controller however getActive() works.
IF I remove the view from the main modules directory I get the expected error response.

hmmmmmmm

Is there any way to debug this?

**Comment by illuminate3** [comment]
Never mind my previous post. Something weird is happening with my install. I deleted the package and reran composer and then deleted my config/themes file. Something must have gotten corrupted ...

**Comment by illuminate3** [comment]
Going to reopen this since issue is similar.

wanted location
```
public/themes/bootstrap/views/app.blade.php
```

view:
```
@extends('app')
```

When I'm trying to use my "default" I keep coming up with view not found. If I place that main "default" file within the resources/views directory I don't get the issue. Also, even if I do place a copy within my template directory the resource view is still being called.

Is this proper functionality?

**Comment by kaidesu** [comment]
Gotta reference the theme namespace.

```php
@extends('bootstrap::app')
```

**Comment by illuminate3** [comment]
ugh! facpalm :dizzy_face:
