### ISSUE TITLE
Theme Layout broken - Laravel 5.4

### ISSUE THREAD

**Issue by johnhearfield** [caffeinated/themes#56]
I can't seem to get the `Theme::setLayout($layout)` to work

`Theme::setLayout` always returns false, so I cant do `@extend($theme_layout)`

File structure:
`/laravel/public/themes/standard/views/layouts/default.blade.php`

Inside `Controller.php`

```
public function __construct() {
        $theme = config('themes.active');
        \Theme::setActive($theme);
        dd(\Theme::setLayout('layouts.default'));
}
```

I've also tried `extend('standard::layouts.default')` and it throws
```
ErrorException thrown with message "No hint path defined for [standard]. (View: /laravel/app/Modules/Dashboard/Resources/Views/dashboard.blade.php)"
```

**Comment by nermamax** [comment]
hi did you manage to get this working?
