### ISSUE TITLE
After I did a Composer Update I got the following error which I think is caused by your package

### ISSUE THREAD

**Issue by hosseinhkj** [caffeinated/themes#6]
InvalidArgumentException in FileViewFinder.php line 140: View [] not found.

in FileViewFinder.php line 140
at FileViewFinder->findInPaths('', array(false)) in FileViewFinder.php line 77
at FileViewFinder->find('') in Factory.php line 145
at Factory->make(null, array('theme_layout' => 'bootstrap::admin.app')) in Themes.php line 228
at Themes->renderView(null, array()) in Themes.php line 210

**Comment by kaidesu** [comment]
I assume this is with v1.2? If so, you'll need to update your theme config file if you haven't done so already.

See [here](https://github.com/caffeinated/themes/blob/62b71c81d247ac9a5a4791c052839b45864d1233/src/config/themes.php) for the updated config.

**Comment by hosseinhkj** [comment]
These commands did the trick after the "composer update"

- php artisan vendor:publish --force
- php artisan config:clear

**Comment by kaidesu** [comment]
Awesome, so everything is in working order for you?

**Comment by hosseinhkj** [comment]
Yes, thanks for the help.

**Comment by kaidesu** [comment]
:+1:
