### ISSUE TITLE
How to make redirect view for 4.0 version?

### ISSUE THREAD

**Issue by oLDu67** [caffeinated/themes#61]
I used version 3. It makes redirect to view in the controller.

`return Theme::view('frontend.index', compact(
                'var1',
                    'var2',
            ))->render();
`

 But how to make redirect to view with version v4.0.2?

Thanks @kaidesu

**Comment by kaidesu** [comment]
With v4 you may simply use the native `view` method - the package automatically hooks into this process to resolve the correct view to load (whether its from your theme or your root app)
