### ISSUE TITLE
Method setActive does not exist.

### ISSUE THREAD

**Issue by xbust3r** [caffeinated/themes#63]
I updated to laravel 5.5 and have a problem with this function:

Theme::setActive('template2');

In the version 5.3 all works fine, I update the module by composer and check the service provider  & facade and is well configured.

Is a bug in laravel 5.5? I use these modules too:
- Caffenaited Modules
- Caffenaited Flash
- Caffenaited Shinobi

**Comment by Uhelliton** [comment]
@xbust3r  
I have the same problem!

**Comment by vtscarlos** [comment]
Nothing?

**Comment by dariusj18** [comment]
It looks to me like the method was changed to setCurrent()
