### ISSUE TITLE
Erro Method view does not exist.

### ISSUE THREAD

**Issue by Uhelliton** [caffeinated/themes#66]
I made the whole package configuration, but I return this error: Method view does not exist., I'm using Laravel 5.5.

Thanks!!!

**Comment by lpm17** [comment]
The method `Them::view()` has been removed as of v4.0. see https://github.com/caffeinated/themes/releases/tag/v4.0 .
If using v4.0 or above you can use the standard Laravel view() method. Caffeinated Themes will auto-resolve the view based on the currently set theme.
