### ISSUE TITLE
Object of class Caffeinated\Manifest\Manifest could not be converted to string

### ISSUE THREAD

**Issue by InkedCurtis** [caffeinated/themes#71]
The issue arises on this code, bare in mind I'm running v4.0.4

```
@foreach(Theme::all() as $theme)
    @if(Theme::getProperty($theme.'::public'))
        <option value="{{url('theme/' . $theme)}}">{{ Theme::getProperty($theme.'::name', 'Unknown Name') }}</option>
    @endif
@endforeach
```

As I can see, this function no longer exists? so how would I replicate such functionality on v4.0.4?

**Comment by kaidesu** [comment]
`Theme`s return themselves as a collection, so while looping through them you may simply access any property values as you normally would through any collection:

`{{ $theme->name or 'Unknown Name' }}`

Sorry for the confusion, I'll get the documentation updated on this~ let me know if you have any other issues/questions!
