### ISSUE TITLE
Problem with 5.6

### ISSUE THREAD

**Issue by hernandes** [caffeinated/themes#72]
I'm doing some testing but it's not working.

In providers node
![image](https://user-images.githubusercontent.com/415107/39758392-19f32568-52a6-11e8-8f6f-1d4816050b56.png)

In aliases node
![image](https://user-images.githubusercontent.com/415107/39758430-38720694-52a6-11e8-9576-40cc3bd3f1c1.png)

Config file
![image](https://user-images.githubusercontent.com/415107/39758451-456d6ca8-52a6-11e8-8803-dce10e947d17.png)

public structure
![image](https://user-images.githubusercontent.com/415107/39758477-579733b4-52a6-11e8-97b1-af7bd06add11.png)

welcome.blade.php in theme folder
![image](https://user-images.githubusercontent.com/415107/39758498-6ad2ba98-52a6-11e8-8a10-8fdf9cb3a210.png)

and result on browser
![image](https://user-images.githubusercontent.com/415107/39758532-7f5dcc1e-52a6-11e8-8a3c-6040dceb1adf.png)

Sorry if I'm doing something wrong.

**Comment by nguyentranchung** [comment]
@hernandes In AppServiceProvider@boot function you should add
```php
\Theme::set('default');
```
I feel somewhat confused as to why it does not load automatically

**Comment by nguyentranchung** [comment]
@hernandes 

search in caffeinated\themes with "active" keyword and you see, never been using

**Comment by nguyentranchung** [comment]
ping @kaidesu
