### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by skalero01** [caffeinated/themes#82]
In your documentation you dont have any information about how to call the assets on the layout view, i tried adding the `{{ Theme::path('public/css/style.css') }}` on the view but i am getting on the browser the next error `Not allowed to load local resource: file:///C:/laragon/www/xxx/themes/xxx/public/css/style.css`

Your documentation on the website doesnt say anything about assets and the wiki on here is not updated. How should this be solved?

**Comment by UnderlineWords** [comment]
There was a 'asset' method on previous versions for asset functionality. Take a look at;
https://github.com/caffeinated/themes/blob/d24ec3230372245e021c5c4583c9ef938ea0352e/src/Themes.php#L361
I guess it was removed from [Themes](https://github.com/caffeinated/themes/blob/d24ec3230372245e021c5c4583c9ef938ea0352e/src/Themes.php) class.

**Comment by tpaksu** [comment]
Any news about this issue?

**Comment by tpaksu** [comment]
I fixed it with: `<link href="{{ asset('themes/'.\Theme::getCurrent().'/css/theme.css') }}" rel="stylesheet">`. Same with the JS file.

**Comment by kaidesu** [comment]
I assume these references are within your theme's layout - what's the use case for pulling a reference of the current theme when you know you're working with a specific theme?

Just reference the theme directly :+1:

```
<link href="{{ asset('themes/bootstrap/css/theme.css') }}" rel="stylesheet">
```
