### ISSUE TITLE
Theme::view() seems to default to /resources/views regardless of public/theme

### ISSUE THREAD

**Issue by merfed** [caffeinated/themes#9]
It seems ```Theme::view()``` is not finding the view inside of a themes folder even if it exists. Folder structure is as so: ```public/themes/default/views/welcome.blade.php```. The active theme is set as default, and the ```$views``` array outputs:

```
  'theme' => string 'default::welcome' (length=16)
  'parent' => string 'default::welcome' (length=16)
  'module' => null
  'base' => string 'welcome' (length=7)
```

```$this->viewFactory->exists($view)``` returns false on all accounts until base, where it finds it.

No idea if this is a bug, or if I'm just missing something.

**Comment by latelatelate** [comment]
I have also noticed this. I can setActive, call all() and see themes in my themes dir, but am seeing the same thing as merfed. When checking if the theme file exists, it doesnt detect xxxxxx::xxxxxx names

Am I just missing something here too?? Thanks :)

**Comment by kaidesu** [comment]
Looks like @merfed's directory structure is correct, they stated that their themes view file is at:

```
public/themes/default/views/welcome.blade.php
```

This could be a bug. I'll be sure to look into this more soon and get back to you guys on the matter. Just wanted to reply right now so you know this isn't being over-looked!

**Comment by irineujunior** [comment]
@merfed , maybe You should update your config/themes.php like I did.

https://github.com/caffeinated/themes/blob/62b71c81d247ac9a5a4791c052839b45864d1233/src/config/themes.php

**Comment by kaidesu** [comment]
Was unable to reproduce this. Please check all your configuration settings to make sure everything is set up correctly.
