### ISSUE TITLE
First Setup - Str::slug error

### ISSUE THREAD

**Issue by ByJacoB27** [caffeinated/themes#96]
` php artisan make:theme Default
   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Illuminate\Support\Facades\Str' not found`

> 77 | $slug   = Str::slug($this->argument('slug'));

> composer.json
> 
> "laravel/framework": "^6.2",
>

**Comment by thewebartisan7** [comment]
I see the same, this https://github.com/caffeinated/themes/blob/master/src/Console/GenerateTheme.php#L6 should be:

use Illuminate\Support\Str;

see https://github.com/caffeinated/themes/pull/97/files

**Comment by ByJacoB27** [comment]
thankx problem fixed :)
